baseURL = 'https://dceoy.github.io/vfft/'
languageCode = 'en-us'
title = 'VFFT'
theme = 'newsroom'
author = 'Daichi Narushima, Ph.D.'
copyright = 'Copyright (c) 2021 - Daichi Narushima, Ph.D.'
canonifyurls = true
paginate = 6

[markup]
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false
    xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    tabWidth = 2

[params]
  locale = 'en_US'
  # ga_analytics = '' # google analytics ID e.g UA-116386578-1
  # ga_verify = '' # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  twitter = '@dceoy'
  # mainSections = ['blog', 'docs'] see https://gohugo.io/functions/where/#mainsections
  disableDarkMode = false
