---
version: '3'

services:
  hugo:
    container_name: hugo
    image: dceoy/hugo:latest
    user: ${UID}:${GID}
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/blog
    working_dir: /blog
    entrypoint:
      - hugo
    command:
      - server
      - --bind=0.0.0.0
      - --theme=newsroom
      - --buildDrafts
      - --watch
